Add HAP doorbell input type
mongoose-os-apps/shelly-homekit pull request #495
Opened 2021-02-12 22:14 UTC by ZeevoX

* Refactored out bulk of `stateless_switch` into `stateless_switch_base` to avoid code duplication
* Added simple `doorbell` service based on `stateless_switch_base`
* Fix #375

2021-02-12 22:44 UTC, andyblac commented
@ZeevoX this should help with adding https://github.com/mongoose-os-apps/shelly-homekit/issues/74 correct ? stateless base i mean

2021-02-12 22:53 UTC, ZeevoX commented
@andyblac from what I gather that issue is about a dummy switch that persists state. This is a stateless switch so I don't see how it would fit in with the example they provided, but perhaps I didn't understand correctly?

2021-02-12 22:55 UTC, andyblac commented
ah, ye, ignore me, must half a sleep, be long day 😄

2021-02-13 13:21 UTC, rojer requested changes
mostly looks good, see a few comments inline.
also, please add copyright blurb to new files (i made them generic)
and run "make format" to make sure formatting is in order (would be nice to add to github action as well).

2021-02-13 19:53 UTC, ZeevoX commented on src/shelly_hap_doorbell.hpp
> +  virtual Type type() const override;
my IDE highlights it if I remove `virtual` due to MISRA C++ rule 10-3-2

![image](https://user-images.githubusercontent.com/8385172/107859735-66156e00-6e33-11eb-8a14-8bcb196294e4.png)

2021-02-13 20:51 UTC, rojer commented on src/shelly_hap_doorbell.hpp
> +  virtual Type type() const override;
looks like outdated MISRA rules are being used. "override" specifier is enough.
i am not familiar with MISRA C++ but i can find exact same wording in MISRA C++ from 2008 (i.e. pre C++11) and in later revision from 2014 it's been modified to sound as follows:

Rule A10-3-2 (required, implementation, automated)
Each overriding virtual function shall be declared with the override or final specifier.


in your IDE you may need to adjust the C++ standard that the code is written to comply with, in our case it's C++11

2021-02-14 08:24 UTC, ZeevoX commented on src/shelly_hap_doorbell.hpp
> +  virtual Type type() const override;
I ended up disabling MISRA altogether since the IDE only knows the 2008 rules. Thank you for looking into this!

2021-02-14 11:49 UTC, rojer approved these changes
LGTM, one minor nit

2021-02-14 11:49 UTC, rojer commented on fs_src/script.js
> +      console.log("Unhandled component type: " + cd.type);
we recently switched to JS string templates (in 84c5376e).

2021-02-14 11:49 UTC, rojer commented on fs_src/script.js
> +      console.log("Unhandled component type: " + cd.type);
same here

2021-02-14 11:58 UTC, merged

2021-02-14 11:59 UTC, rojer commented
very good, thank you!