Shelly1/PM: Support Addon as Switch (Input)
mongoose-os-apps/shelly-homekit pull request #967
Opened 2022-03-20 08:56 UTC by markirb

This would enable an additional Switch via the Addon (e.g. magnetic sensor), for Default mode as well as Garage Door Opener as e.g. requested here:

https://github.com/mongoose-os-apps/shelly-homekit/issues/713

I have nothing to test this with so far, but maybe someone with the appropriate equipment would be able to?

This defaults to momentary switch in Default mode - maybe it should be "Contact Sensor"? But it could be used as many things...

2022-03-20 20:03 UTC, rojer commented
did a quick review, don't like the approach. using sys mode for this is a big streatch.

here's my thinking:

1) we can detect presence of addon by probing if driving GPIO3 affects GPIO0
2) if addon is detected and there are no tempperature sensors, use it as an additional input
3) in switch mode, export this input as stateless / smoke sensor / whatever
4) in gdo mode, incorporate this additional input as "fully open" sensor

2022-03-20 20:04 UTC, rojer requested changes
see above

2022-03-20 21:24 UTC, markirb commented
Seems reasonable and not complicated, have some WIP, not finished yet

2022-03-22 15:38 UTC, markirb commented
I changed it, and tested it as far as I can on my setup, but not with the real switch attached...

@rojer: I spent some thought: can we really detect the addon in the field, with a switch attached?
When there is a real switch attached the input is driven eventually by two sources. Why should the output pin always win, is there a resistor that guarantees this behavior?

2022-06-05 18:59 UTC, rojer commented
sorry, i dropped the ball on this one. good point about the switch, i didn't think of that initially. but i still think we can auto-detect the presence of the add-on or an external switch as follows:
1) configure GPIO3 as input with pull-up, if it's low it means an external switch is pulling it low, configure as input, no need to test for sensors as the bus is low. if it's high, move on to 2
2) reconfigure as output and do the toggle test to detect the add-on, check for temp sensors and fall back to configuring as input

2022-11-19 13:32 UTC, HarrySteff commented
Are there any news regarding this?

2022-11-20 15:51 UTC, markirb commented
Just pushed the changes I had lying around. I cannot test it, the question is: can you @HarrySteff ?

2022-11-20 16:15 UTC, HarrySteff commented
@markirb  thanks, I could, but I need a hint how I can test it? If I press update at web-interface, it says „up to date

2022-11-20 18:40 UTC, markirb commented
Try this file... its for the Shelly1
[fw.zip](https://github.com/mongoose-os-apps/shelly-homekit/files/10050434/fw.zip)

2022-11-20 18:55 UTC, HarrySteff commented
Thank you very much. I’ll try it later..

2022-11-22 20:33 UTC, markirb commented
Mhhh that is strange. Right now you cannot do more I guess. I will have to try something, not sure when I will find the time

2022-11-22 20:37 UTC, HarrySteff commented
Many many thanks, I will stay tuned… do some more tests. If I figure out something, I will let you know! Thanks again!

2022-11-23 21:54 UTC, markirb commented
mhh i checked the addon detection. it should work, at least it does for me...
what did you set the "open sensor" to?
can you maybe post some logs of your device when it is open/closed?

2022-11-23 22:22 UTC, HarrySteff commented
![2608169A-9023-4F4D-806D-071E7DC04495](https://user-images.githubusercontent.com/3635718/203655719-6f1b177c-7a31-4aeb-8ed2-5257f35cc141.jpeg)


Here logfile, first I open the garage door, then I closed it:

`271715038175 shelly_debug.cpp:231    No log file, sending new entries
271715304367 shelly_main.cpp:458     Up 271715.29, HAP 0/1/12 ns 1, RAM: 27428/19800; st 0; 5.1: cur:stopped tgt:closed cl:0 op:-1
271723304385 shelly_main.cpp:458     Up 271723.29, HAP 0/1/12 ns 1, RAM: 27428/19800; st 0; 5.1: cur:stopped tgt:closed cl:0 op:-1
271725002945 mgos_http_server.c:180  0x3fff5644 HTTP connection from 192.168.0.117:61827
271727016980 mgos_http_server.c:180  0x3fff56fc HTTP connection from 192.168.0.117:61828
271727077532 mg_rpc.c:310            Shelly.GetInfo via WS_in 192.168.0.117:61828
271727132135 mg_rpc.c:310            Shelly.GetInfoExt via WS_in 192.168.0.117:61828
271727972936 mg_rpc.c:310            Shelly.GetInfoExt via WS_in 192.168.0.117:61828
271728980947 mg_rpc.c:310            Shelly.GetInfoExt via WS_in 192.168.0.117:61828
271729972716 mg_rpc.c:310            Shelly.GetInfoExt via WS_in 192.168.0.117:61828
271730977023 mg_rpc.c:310            Shelly.GetInfoExt via WS_in 192.168.0.117:61828
271731304744 shelly_main.cpp:458     Up 271731.29, HAP 0/1/12 ns 1, RAM: 26644/19800; st 0; 5.1: cur:stopped tgt:closed cl:0 op:-1
271731975797 mg_rpc.c:310            Shelly.GetInfoExt via WS_in 192.168.0.117:61828
271732978039 mg_rpc.c:310            Shelly.GetInfoExt via WS_in 192.168.0.117:61828
271733979625 mg_rpc.c:310            Shelly.GetInfoExt via WS_in 192.168.0.117:61828
271734981069 mg_rpc.c:310            Shelly.GetInfoExt via WS_in 192.168.0.117:61828
271735199722 mg_rpc.c:310            Shelly.SetState via WS_in 192.168.0.117:61828
271735206017 shelly_output.cpp:63    Output 1: off -> on (GDO:open)
271735213179 shelly_hap_garage_d:307 GDO 1: Tgt State: closed -> open (1 -> 0) (fixup)
271735220189 shelly_hap_garage_d:222 GDO 1: Cur State: stopped -> opening (4 -> 2)
271735292372 mg_rpc.c:310            Shelly.GetInfoExt via WS_in 192.168.0.117:61828
271735512733 shelly_output.cpp:63    Output 1: on -> off (pulse_off)
271735908900 shelly_input.cpp:76     Input 2: change (state 0)
271736002595 mg_rpc.c:310            Shelly.GetInfoExt via WS_in 192.168.0.117:61828
271736980891 mg_rpc.c:310            Shelly.GetInfoExt via WS_in 192.168.0.117:61828
271738003006 mg_rpc.c:310            Shelly.GetInfoExt via WS_in 192.168.0.117:61828
271739304767 shelly_main.cpp:458     Up 271739.29, HAP 0/1/12 ns 1, RAM: 26824/19800; st 0; 5.1: cur:opening tgt:open cl:0 op:-1
271744107595 mg_rpc.c:310            Shelly.GetInfoExt via WS_in 192.168.0.117:61828
271745109086 mg_rpc.c:310            Shelly.GetInfoExt via WS_in 192.168.0.117:61828
271746113932 mg_rpc.c:310            Shelly.GetInfoExt via WS_in 192.168.0.117:61828
271747124901 mg_rpc.c:310            Shelly.GetInfoExt via WS_in 192.168.0.117:61828
271747304888 shelly_main.cpp:458     Up 271747.29, HAP 0/1/12 ns 1, RAM: 26656/19800; st 0; 5.1: cur:opening tgt:open cl:0 op:-1
271748112765 mg_rpc.c:310            Shelly.GetInfoExt via WS_in 192.168.0.117:61828
271749127207 mg_rpc.c:310            Shelly.GetInfoExt via WS_in 192.168.0.117:61828
271750138458 mg_rpc.c:310            Shelly.GetInfoExt via WS_in 192.168.0.117:61828
271750264677 shelly_hap_garage_d:222 GDO 1: Cur State: opening -> open (2 -> 0)
271751112674 mg_rpc.c:310            Shelly.GetInfoExt via WS_in 192.168.0.117:61828
271752114332 mg_rpc.c:310            Shelly.GetInfoExt via WS_in 192.168.0.117:61828
271753121546 mg_rpc.c:310            Shelly.GetInfoExt via WS_in 192.168.0.117:61828
271754120827 mg_rpc.c:310            Shelly.GetInfoExt via WS_in 192.168.0.117:61828
271755122168 mg_rpc.c:310            Shelly.GetInfoExt via WS_in 192.168.0.117:61828
271755304034 shelly_main.cpp:458     Up 271755.29, HAP 0/1/12 ns 1, RAM: 26832/19800; st 0; 5.1: cur:open tgt:open cl:0 op:-1
271755375730 mg_rpc.c:310            Shelly.SetState via WS_in 192.168.0.117:61828
271755382133 shelly_output.cpp:63    Output 1: off -> on (GDO:close)
271755389105 shelly_hap_garage_d:307 GDO 1: Tgt State: open -> closed (0 -> 1) (RPC)
271755395837 shelly_hap_garage_d:222 GDO 1: Cur State: open -> closing (0 -> 3)
271755481458 mg_rpc.c:310            Shelly.GetInfoExt via WS_in 192.168.0.117:61828
271755688643 shelly_output.cpp:63    Output 1: on -> off (pulse_off)
271756131372 mg_rpc.c:310            Shelly.GetInfoExt via WS_in 192.168.0.117:61828
271757121637 mg_rpc.c:310            Shelly.GetInfoExt via WS_in 192.168.0.117:61828
271763304499 shelly_main.cpp:458     Up 271763.29, HAP 0/1/12 ns 1, RAM: 26824/19800; st 0; 5.1: cur:closing tgt:closed cl:0 op:-1
271764747746 shelly_input.cpp:76     Input 2: change (state 1)
271765754271 shelly_input.cpp:76     Input 2: long (state 1)
271770462053 shelly_hap_garage_d:222 GDO 1: Cur State: closing -> stopped (3 -> 4)
271771304600 shelly_main.cpp:458     Up 271771.29, HAP 0/1/12 ns 1, RAM: 26824/19800; st 0; 5.1: cur:stopped tgt:closed cl:0 op:-1
271779304722 shelly_main.cpp:458     Up 271779.29, HAP 0/1/12 ns 1, RAM: 26824/19800; st 0; 5.1: cur:stopped tgt:closed cl:0 op:-1
271787304806 shelly_main.cpp:458     Up 271787.29, HAP 0/1/12 ns 1, RAM: 26824/19800; st 0; 5.1: cur:stopped tgt:closed cl:0 op:-1`

2022-11-23 22:25 UTC, markirb commented
May I ask why you disabled it?

2022-11-23 22:29 UTC, HarrySteff commented
I have only one Reed Sensor installed. And this is „closed“ if the garage door is closed, if I open the door there isn’t another reed sensor… did. I understand something wrong?

2022-11-23 22:40 UTC, markirb commented
Yes: see here

https://github.com/mongoose-os-apps/shelly-homekit/wiki/Garage-Door-Opener-Settings

2022-11-23 22:48 UTC, HarrySteff commented
Sorry maybe I’m stupid… I do not understand. 
the link you have posted here did not say anything about the addon. I didn’t have connected a cable to the „SW“ of my Shelly1 because it is powered by 220V

2022-11-23 22:53 UTC, HarrySteff commented
It seems to work with this Settings:

![BFAF79C5-48E8-436D-BE3E-576BCE754A6E](https://user-images.githubusercontent.com/3635718/203659538-1d47fa29-13c7-45d8-9f7d-e353f729379f.jpeg)

?!?

2022-11-24 07:01 UTC, markirb commented
Sorry. For explanation:
GDO supports two sensors:
One that says if it's open, one if it's closed.
The closed one is currently attached to SW. You are of course very right not to attach your sensor to 230V !!!! This would have to be done via som kind of isolating circuit as the Shelly Addon. 
With this pull request the GDO uses the addon as open sensor. Which of course is only a software limitation to swap the two inputs. This could be addressed in a separate feature.
However thank you for the testing ad this says this PR is working and could be merged @rojer 

So now I understand you have your closed sensor on the input of the open sensor :)

2022-11-24 11:41 UTC, vistalba commented
Hardware available. Will test next week with my garage door! Many thanks @markirb

2022-11-30 10:55 UTC, vistalba commented
Tested on my Shelly1+Addon+ 2 magnetic sensors on a Hörmann garage door.
Works as expected for me.

2022-12-25 13:27 UTC, vistalba commented
@rojer Any plan for official release?

2022-12-25 13:52 UTC, timoschilling commented
> One thing that I see is that when I try to open "Log" I do get 401 error. Is this expected?

do you have set a password? If yes it’s expected or better it’s a know bug

2022-12-26 15:15 UTC, vistalba commented
> > One thing that I see is that when I try to open "Log" I do get 401 error. Is this expected?
> 
> do you have set a password? If yes it’s expected or better it’s a know bug

I have a password set. So then this is not because of this release. It a known bug. So for me everything works fine.

2023-04-03 23:09 UTC, Plasticainen commented
Hi, Shelly 2PM not support?

2023-04-04 08:46 UTC, timoschilling commented
@Plasticainen the Plus models have a different addon support for that will be handled in #1146

2023-04-04 10:23 UTC, vistalba commented
Any plan for meging it into official release?

2023-04-04 21:10 UTC, timoschilling commented
@vistalba sure when it’s ready

2023-11-09 21:20 UTC, markirb commented
@timoschilling what is not ready on this PR? Could you merge this. Then DHT can be merged with refactoring and code from this PR

2023-11-10 07:50 UTC, timoschilling commented
@markirb It's still marked as `draft` so I never tock a deeper lock on it

2023-11-10 08:44 UTC, markirb commented
That explains it. This was tested, i think it is fine.... so yes please review

2024-02-07 19:24 UTC, markirb commented
Contained in other branch closing this

2024-02-07 19:24 UTC, closed without merging